### ISSUE TITLE
Touhou games don't launch when I use the script

### ISSUE THREAD

**Issue by SomeRandomGuy64** [tactikauan/thcrap-steam-proton-wrapper#2]
Ok so I tried using the script and the games don't launch, however when I remove this if statement:

------------------------------------------------------------------------------------------
if [ -z "$COMMAND" ]; then
    shift "$(($OPTIND -1))"
    COMMAND=''
    # Quote all arguments that contain whitespace
    for i in "$@"; do
        [[ $i =~ ( ) ]] && i=${i@Q}
        COMMAND="$COMMAND $i"
    done
fi
------------------------------------------------------------------------------------------

it starts working again.

You might want to try and fix this or at least remove this bit until you can find a fix

**Comment by nerusuki** [comment]
Can you provide the launch options you're using so I can debug it?

**Comment by nerusuki** [comment]
Also, what's the output of `ls -l /bin/sh`?

**Comment by nerusuki** [comment]
Closing since I believe this has been fixed in 0dee52f7f1db4c9e1eeccac6c880bc3e8b1b973f
